[package]
name = "axum_first"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8" 
tokio = { version = "1.46.1", features = ["full"] }
hyper = "1.0" 
tower = "0.5" 
serde = { version = "1.0", features = ["derive"] }