[package]
name = "seaorm_sqlit3"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version = "1.42",features =["full"]}
sea-orm ={version = "1.1.0",features = ["sqlx-sqlite","runtime-tokio-native-tls"]}